---
 - name: Playbook configure NanoPi as a Prodmon device
   hosts: nanopi
   become: true
   tasks: 
    - name: Ansible apt install dependancies
      ansible.builtin.apt:
        name: 
          - nano
          - python3
          - python3-pip
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Git clone Prodmon
      ansible.builtin.git:
        repo: https://github.com/cstrutton/prodmon.git
        dest: /opt/prodmon

    - name: Install Prodmon and dependancies
      ansible.builtin.pip:
        chdir: /opt/prodmon
        name: .

    - name: Add eth1 config
      ansible.builtin.template:
        src: eth1.src
        dest: /etc/network/interfaces.d/eth1

    - name: config version
      ansible.builtin.file:
        path: /home/pi/config.ver.1
        state: touch
